# Generated by Django 4.0.1 on 2022-02-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='photos/logo.jpg', null=True, upload_to='photos/'),
        ),
    ]
